services:
  - type: web
    name: eureka-server
    runtime: image
    image:
      url: rahman5187/eureka-server:latest
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "8761"
      - key: EUREKA_HOSTNAME
        value: eureka-server

  - type: web
    name: api-gateway
    runtime: image
    image:
      url: rahman5187/api-gateway:v2.2.0
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: EUREKA_URL
        value: https://eureka-server-3nyd.onrender.com/eureka/
      - key: JWT_SECRET
        value: EA4L1qbX+OmMmn+6Cv2OXxgHSAFRlxE+Y/8Na58u5eY=
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:4200,https://pharmacy-frontend-b6j5.onrender.com

  - type: web
    name: user-service
    runtime: image
    image:
      url: rahman5187/user-service:latest
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "8081"
      - key: EUREKA_URL
        value: https://eureka-server-3nyd.onrender.com/eureka/
      - key: EUREKA_HOSTNAME
        value: user-service
      - key: DB_URL
        value: jdbc:mysql://mysql-3c385771-syedrahman5187-pharmacy.l.aivencloud.com:28766/pharmacy_db?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_YsvLGCGwf9qq8gSo5xk
      - key: JWT_SECRET
        value: EA4L1qbX+OmMmn+6Cv2OXxgHSAFRlxE+Y/8Na58u5eY=

  - type: web
    name: order-service
    runtime: image
    image:
      url: rahman5187/order-service:latest
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "8082"
      - key: EUREKA_URL
        value: https://eureka-server-3nyd.onrender.com/eureka/
      - key: EUREKA_HOSTNAME
        value: order-service
      - key: DB_URL
        value: jdbc:mysql://mysql-3c385771-syedrahman5187-pharmacy.l.aivencloud.com:28766/order_db?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_YsvLGCGwf9qq8gSo5xk
      - key: RABBITMQ_HOST
        value: fuji.lmq.cloudamqp.com
      - key: RABBITMQ_PORT
        value: "5671"
      - key: RABBITMQ_USERNAME
        value: inzniazk
      - key: RABBITMQ_PASSWORD
        value: vw_LbH0xVLCQCFTKEut1zBYSx14SUkdY
      - key: RABBITMQ_VIRTUAL_HOST
        value: inzniazk
      - key: RABBITMQ_SSL_ENABLED
        value: "true"
      - key: SPRING_RABBITMQ_ADDRESSES
        value: amqps://inzniazk:vw_LbH0xVLCQCFTKEut1zBYSx14SUkdY@fuji.lmq.cloudamqp.com:5671/inzniazk
      - key: INVENTORY_SERVICE_URL
        value: https://supplier-inventory-service.onrender.com
      - key: PAYMENT_SERVICE_URL
        value: https://payment-service-4w2d.onrender.com

  - type: web
    name: supplier-inventory-service
    runtime: image
    image:
      url: rahman5187/supplier-inventory-service:latest
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "8083"
      - key: EUREKA_URL
        value: https://eureka-server-3nyd.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:mysql://mysql-3c385771-syedrahman5187-pharmacy.l.aivencloud.com:28766/pharmacy_inventory?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_YsvLGCGwf9qq8gSo5xk
      - key: RABBITMQ_HOST
        value: fuji.lmq.cloudamqp.com
      - key: RABBITMQ_PORT
        value: "5671"
      - key: RABBITMQ_USERNAME
        value: inzniazk
      - key: RABBITMQ_PASSWORD
        value: vw_LbH0xVLCQCFTKEut1zBYSx14SUkdY
      - key: RABBITMQ_VIRTUAL_HOST
        value: inzniazk
      - key: RABBITMQ_SSL_ENABLED
        value: "true"
      - key: SPRING_RABBITMQ_ADDRESSES
        value: amqps://inzniazk:vw_LbH0xVLCQCFTKEut1zBYSx14SUkdY@fuji.lmq.cloudamqp.com:5671/inzniazk

  - type: web
    name: notification-service
    runtime: image
    image:
      url: rahman5187/notification-service:latest
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "8084"
      - key: EUREKA_URL
        value: https://eureka-server-3nyd.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:mysql://mysql-3c385771-syedrahman5187-pharmacy.l.aivencloud.com:28766/notification_db?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_YsvLGCGwf9qq8gSo5xk
      - key: RABBITMQ_HOST
        value: fuji.lmq.cloudamqp.com
      - key: RABBITMQ_PORT
        value: "5671"
      - key: RABBITMQ_USERNAME
        value: inzniazk
      - key: RABBITMQ_PASSWORD
        value: vw_LbH0xVLCQCFTKEut1zBYSx14SUkdY
      - key: RABBITMQ_VIRTUAL_HOST
        value: inzniazk
      - key: RABBITMQ_SSL_ENABLED
        value: "true"
      - key: SPRING_RABBITMQ_ADDRESSES
        value: amqps://inzniazk:vw_LbH0xVLCQCFTKEut1zBYSx14SUkdY@fuji.lmq.cloudamqp.com:5671/inzniazk

  - type: web
    name: payment-service
    runtime: image
    image:
      url: rahman5187/payment-service:latest
    region: oregon
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "8085"
      - key: EUREKA_URL
        value: https://eureka-server-3nyd.onrender.com/eureka/
      - key: DB_URL
        value: jdbc:mysql://mysql-3c385771-syedrahman5187-pharmacy.l.aivencloud.com:28766/payment_db?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_YsvLGCGwf9qq8gSo5xk
      - key: RABBITMQ_HOST
        value: fuji.lmq.cloudamqp.com
      - key: RABBITMQ_PORT
        value: "5671"
      - key: RABBITMQ_USERNAME
        value: inzniazk
      - key: RABBITMQ_PASSWORD
        value: vw_LbH0xVLCQCFTKEut1zBYSx14SUkdY
      - key: RABBITMQ_VIRTUAL_HOST
        value: inzniazk
      - key: RABBITMQ_SSL_ENABLED
        value: "true"
      - key: SPRING_RABBITMQ_ADDRESSES
        value: amqps://inzniazk:vw_LbH0xVLCQCFTKEut1zBYSx14SUkdY@fuji.lmq.cloudamqp.com:5671/inzniazk
      - key: JWT_SECRET
        value: EA4L1qbX+OmMmn+6Cv2OXxgHSAFRlxE+Y/8Na58u5eY=
      - key: RAZORPAY_KEY_ID
        value: rzp_test_SkUT7TYdihPuCN
      - key: RAZORPAY_KEY_SECRET
        value: V6C0KvJ3x5g4df05mafrZVbq
      - key: ORDER_SERVICE_URL
        value: https://order-service-l60x.onrender.com
