server.port=${SERVER_PORT:8085}
spring.application.name=PAYMENT-SERVICE

# ✅ DB
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/payment_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:rahman}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ✅ Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

# ✅ RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST:/}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL_ENABLED:false}

# ✅ Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_SkUT7TYdihPuCN}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:V6C0KvJ3x5g4df05mafrZVbq}

# ✅ JWT (same as user service)
jwt.secret=${JWT_SECRET:architect-evaluation-secure-key-1234567890123456}
jwt.expiration=${JWT_EXPIRATION:86400000}
