# Server configuration
server.port=${SERVER_PORT:8761}
spring.application.name=eureka-server

# Eureka server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: Better dashboard visibility
eureka.server.enable-self-preservation=false
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
